server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/carlocodes/bank-config.git
          default-label: master
          clone-on-start: true
